import consultingAgreement from "../draftExamples/consultingAgreement";
import employmentOfferLetter from "../draftExamples/employeeOfferLetter";
import employmentContract from "../draftExamples/employmentContract";
import invoiceForServices from "../draftExamples/invoiceForService";
import jointVentureAgreement from "../draftExamples/jointVentureAgreement";
import leaseAgreement from "../draftExamples/leaseAgreement";
import legalDemandNotice from "../draftExamples/legalDemandNotice";
import loanAgreement from "../draftExamples/loanAgreement";
import memorandumOfUnderstanding from "../draftExamples/menorandumOfUnderstanding";
import nonDisclosureAgreement from "../draftExamples/nonDisclosureAgreement";
import noticeForBreachOfContract from "../draftExamples/noticeForBreachOfContract";
import noticeForRecoveryOfDues from "../draftExamples/noticeForRecoveryOfDues";
import noticeToVacate from "../draftExamples/noticeToVacate";
import partnershipAgreement from "../draftExamples/partnershipAgreement";
import paymentReminderExample from "../draftExamples/paymentReminder";
import promissoryNote from "../draftExamples/promissoryNote";
import serviceAgreement from "../draftExamples/serviceAgreement";
import shareholdersAgreement from "../draftExamples/shareholdersAgreement";
import terminationNotice from "../draftExamples/terminationNotice";

export const fieldSchema: { [key: string]: { label: string; key: string }[] } =
  {
    "payment-reminder": [
      { label: "Date", key: "date" },
      { label: "Reference Number", key: "refNo" },
      { label: "Lawyer Name", key: "lawyerName" },
      { label: "Lawyer Address", key: "lawyerAddress" },
      { label: "Lawyer Phone", key: "lawyerPhone" },
      { label: "Lawyer Email", key: "lawyerEmail" },
      { label: "Recipient Name", key: "recipientName" },
      { label: "Recipient Address", key: "recipientAddress" },
      { label: "Outstanding Amount", key: "amount" },
      { label: "Your Company Name", key: "companyName" },
      { label: "Business Description", key: "businessDescription" },
      { label: "Agreement Date", key: "agreementDate" },
      { label: "Invoice Details", key: "invoiceDetails" },
      { label: "Your Address", key: "yourAddress" },
      { label: "Bank Name", key: "bankName" },
      { label: "Account Holder", key: "accountHolder" },
      { label: "Account Number", key: "accountNumber" },
      { label: "IFSC Code", key: "ifscCode" },
      { label: "Days to Comply", key: "days" },
    ],
    "termination-notice": [
      { label: "To Employee", key: "toEmployee" },
      { label: "From Company", key: "fromCompanpay" },
      { label: "Reason", key: "reason" },
      { label: "Termination Date", key: "date" },
    ],
    "legal-demand-notice": [
      { label: "To Party", key: "toParty" },
      { label: "From Lawyer", key: "fromLawyer" },
      { label: "Claim Details", key: "claimDetails" },
    ],
    "non-disclosure-agreement": [
      { label: "Effective Date", key: "effectiveDate" },
      { label: "Disclosing Party Name", key: "disclosingPartyName" },
      { label: "Disclosing Party Address", key: "disclosingPartyAddress" },
      { label: "Disclosing Party Title", key: "disclosingPartyTitle" },
      { label: "Receiving Party Name", key: "receivingPartyName" },
      { label: "Receiving Party Address", key: "receivingPartyAddress" },
      { label: "Receiving Party Title", key: "receivingPartyTitle" },
      { label: "Purpose", key: "purpose" },
      { label: "Duration", key: "duration" },
      { label: "Jurisdiction", key: "jurisdiction" },
    ],
    "employee-offer-letter": [
      { label: "Date", key: "date" },
      { label: "Candidate Name", key: "candidateName" },
      { label: "Candidate Address", key: "candidateAddress" },
      { label: "Job Title", key: "jobTitle" },
      { label: "Company Name", key: "companyName" },
      { label: "Reporting Manager", key: "reportingManager" },
      { label: "Start Date", key: "startDate" },
      { label: "Annual Salary", key: "annualSalary" },
      { label: "Salary in Words", key: "salaryInWords" },
      { label: "Probation Period", key: "probationPeriod" },
      { label: "Benefits Details", key: "benefitsDetails" },
      { label: "Work Location", key: "workLocation" },
      { label: "Notice Period", key: "noticePeriod" },
      { label: "Authorized Signatory Name", key: "authorizedSignatoryName" },
      { label: "Authorized Signatory Title", key: "authorizedSignatoryTitle" },
    ],
    "lease-agreement": [
      { label: "Agreement Date", key: "agreementDate" },
      { label: "Lessor Name", key: "lessorName" },
      { label: "Lessor Address", key: "lessorAddress" },
      { label: "Lessee Name", key: "lesseeName" },
      { label: "Lessee Address", key: "lesseeAddress" },
      { label: "Property Address", key: "propertyAddress" },
      { label: "Lease Start Date", key: "leaseStartDate" },
      { label: "Lease End Date", key: "leaseEndDate" },
      { label: "Monthly Rent", key: "monthlyRent" },
      { label: "Rent Due Date", key: "rentDueDate" },
      { label: "Rent Payment Address", key: "rentPaymentAddress" },
      { label: "Security Deposit Amount", key: "securityDepositAmount" },
      {
        label: "Utilities Provided by Lessor",
        key: "utilitiesProvidedByLessor",
      },
      { label: "Termination Notice Period", key: "terminationNoticePeriod" },
      { label: "Jurisdiction", key: "jurisdiction" },
    ],
    "service-agreement": [
      { label: "Agreement Date", key: "agreementDate" },
      { label: "Client Name", key: "clientName" },
      { label: "Client Address", key: "clientAddress" },
      { label: "Service Provider Name", key: "serviceProviderName" },
      { label: "Service Provider Address", key: "serviceProviderAddress" },
      { label: "Service Description", key: "serviceDescription" },
      { label: "Start Date", key: "startDate" },
      { label: "End Date", key: "endDate" },
      { label: "Service Fee Amount", key: "serviceFeeAmount" },
      { label: "Service Fee in Words", key: "serviceFeeInWords" },
      { label: "Payment Schedule", key: "paymentSchedule" },
      { label: "Reimbursable Expenses", key: "reimbursableExpenses" },
      { label: "Ownership Clause", key: "ownershipClause" },
      { label: "Termination Notice Period", key: "terminationNoticePeriod" },
      { label: "Jurisdiction", key: "jurisdiction" },
    ],
    "invoice-for-service": [
      { label: "Invoice Number", key: "invoiceNumber" },
      { label: "Invoice Date", key: "invoiceDate" },
      { label: "Service Provider Name", key: "serviceProviderName" },
      { label: "Service Provider Address", key: "serviceProviderAddress" },
      { label: "Service Provider Contact", key: "serviceProviderContact" },
      { label: "Client Name", key: "clientName" },
      { label: "Client Address", key: "clientAddress" },
      { label: "Client Contact", key: "clientContact" },
      { label: "Service Description", key: "serviceDescription" },
      { label: "Service Start Date", key: "serviceStartDate" },
      { label: "Service End Date", key: "serviceEndDate" },
      { label: "Service Fee Amount", key: "serviceFeeAmount" },
      { label: "Tax Amount", key: "taxAmount" },
      { label: "Other Charges", key: "otherCharges" },
      { label: "Total Amount", key: "totalAmount" },
      { label: "Payment Terms", key: "paymentTerms" },
      { label: "Payment Due Date", key: "paymentDueDate" },
      { label: "Payment Methods", key: "paymentMethods" },
      { label: "Account Name", key: "accountName" },
      { label: "Bank Name", key: "bankName" },
      { label: "Account Number", key: "accountNumber" },
      { label: "IFSC or SWIFT Code", key: "ifscOrSwiftCode" },
    ],
    "loan-agreement": [
      { label: "Agreement Date", key: "agreementDate" },
      { label: "Lender Name", key: "lenderName" },
      { label: "Lender Address", key: "lenderAddress" },
      { label: "Borrower Name", key: "borrowerName" },
      { label: "Borrower Address", key: "borrowerAddress" },
      { label: "Loan Amount", key: "loanAmount" },
      { label: "Loan Amount in Words", key: "loanAmountInWords" },
      { label: "Disbursement Date", key: "disbursementDate" },
      { label: "Loan Purpose", key: "loanPurpose" },
      { label: "Interest Rate (%)", key: "interestRate" },
      { label: "Number of Installments", key: "numberOfInstallments" },
      { label: "Installment Amount", key: "installmentAmount" },
      { label: "First Repayment Date", key: "firstRepaymentDate" },
      { label: "Repayment Frequency", key: "repaymentFrequency" },
      { label: "Prepayment Notice Period", key: "prepaymentNoticePeriod" },
      { label: "Collateral Details", key: "collateralDetails" },
      { label: "Jurisdiction", key: "jurisdiction" },
    ],
    "consulting-agreement": [
      { label: "Agreement Date", key: "agreementDate" },
      { label: "Client Name", key: "clientName" },
      { label: "Client Address", key: "clientAddress" },
      { label: "Consultant Name", key: "consultantName" },
      { label: "Consultant Address", key: "consultantAddress" },
      { label: "Scope of Work", key: "scopeOfWork" },
      { label: "Start Date", key: "startDate" },
      { label: "End Date", key: "endDate" },
      { label: "Fee Amount", key: "feeAmount" },
      { label: "Payment Schedule", key: "paymentSchedule" },
      { label: "Termination Notice Period", key: "terminationNoticePeriod" },
      { label: "Jurisdiction", key: "jurisdiction" },
    ],
    "employement-contract": [
      { label: "Agreement Date", key: "agreementDate" },
      { label: "Employer Name", key: "employerName" },
      { label: "Employer Address", key: "employerAddress" },
      { label: "Employee Name", key: "employeeName" },
      { label: "Employee Address", key: "employeeAddress" },
      { label: "Job Title", key: "jobTitle" },
      { label: "Reporting Manager", key: "reportingManager" },
      { label: "Start Date", key: "startDate" },
      { label: "Salary Amount", key: "salaryAmount" },
      { label: "Payment Frequency", key: "paymentFrequency" },
      { label: "Benefits Details", key: "benefitsDetails" },
      { label: "Probation Period", key: "probationPeriod" },
      { label: "Probation Notice Period", key: "probationNoticePeriod" },
      { label: "Working Hours", key: "workingHours" },
      { label: "Leave Days per Year", key: "leaveDays" },
      { label: "Non-Compete Duration", key: "nonCompeteDuration" },
      { label: "Employer Notice Period", key: "employerNoticePeriod" },
      { label: "Employee Notice Period", key: "employeeNoticePeriod" },
      { label: "Jurisdiction", key: "jurisdiction" },
      { label: "Authorized Signatory Name", key: "authorizedSignatoryName" },
      { label: "Authorized Signatory Title", key: "authorizedSignatoryTitle" },
    ],
    "partnership-agreement": [
      { label: "Date", key: "date" },
      { label: "Partner One Name", key: "partnerOneName" },
      { label: "Partner One Address", key: "partnerOneAddress" },
      { label: "Partner Two Name", key: "partnerTwoName" },
      { label: "Partner Two Address", key: "partnerTwoAddress" },
      { label: "Jurisdiction", key: "jurisdiction" },
      { label: "Partnership Name", key: "partnershipName" },
      { label: "Business Purpose", key: "businessPurpose" },
      { label: "Partner One Contribution", key: "partnerOneContribution" },
      { label: "Partner Two Contribution", key: "partnerTwoContribution" },
      { label: "Partner One Share (%)", key: "partnerOneShare" },
      { label: "Partner Two Share (%)", key: "partnerTwoShare" },
    ],
    "joint-venture-agreement": [
      { label: "Party One Name", key: "partyOneName" },
      { label: "Party One Address", key: "partyOneAddress" },
      { label: "Party Two Name", key: "partyTwoName" },
      { label: "Party Two Address", key: "partyTwoAddress" },
      { label: "Business Purpose", key: "businessPurpose" },
      { label: "Party One Contribution", key: "partyOneContribution" },
      { label: "Party Two Contribution", key: "partyTwoContribution" },
      { label: "Profit Sharing Ratio", key: "profitSharingRatio" },
      { label: "Management Structure", key: "managementStructure" },
      { label: "Start Date", key: "startDate" },
      { label: "End Date", key: "endDate" },
      { label: "Jurisdiction", key: "jurisdiction" },
      { label: "Date", key: "date" },
    ],
    "promissory-note": [
      { label: "Lender Name", key: "lenderName" },
      { label: "Borrower Name", key: "borrowerName" },
      { label: "Loan Amount", key: "loanAmount" },
      { label: "Interest Rate (%)", key: "interestRate" },
      { label: "Due Date", key: "dueDate" },
      { label: "Payment Method", key: "paymentMethod" },
    ],
    "shareholders-agreement": [
      { label: "Date", key: "date" },
      { label: "Company Name", key: "companyName" },
      { label: "Shareholder Names", key: "shareholderNames" },
      { label: "Shareholding Details", key: "shareholdingDetails" },
      { label: "Board Representation", key: "boardRepresentation" },
      { label: "Dispute Resolution Method", key: "disputeResolutionMethod" },
      { label: "Jurisdiction", key: "jurisdiction" },
    ],
    "memorandum-of-understanding": [
      { label: "Party A", key: "partyA" },
      { label: "Party B", key: "partyB" },
      { label: "Purpose", key: "purpose" },
      { label: "Party A Responsibilities", key: "partyAResponsibilities" },
      { label: "Party B Responsibilities", key: "partyBResponsibilities" },
      { label: "Start Date", key: "startDate" },
      { label: "End Date", key: "endDate" },
    ],
    "notice-to-vacate": [
      { label: "Tenant Name", key: "tenantName" },
      { label: "Tenant Address", key: "tenantAddress" },
      { label: "Landlord Name", key: "landlordName" },
      { label: "Landlord Address", key: "landlordAddress" },
      { label: "Property Address", key: "propertyAddress" },
      { label: "Vacate Date", key: "vacateDate" },
      { label: "Reason for Eviction", key: "reasonForEviction" },
      { label: "Notice Period (Days)", key: "noticePeriod" },
    ],
    "notice-for-breach-of-contract": [
      { label: "Recipient Name", key: "recipientName" },
      { label: "Recipient Address", key: "recipientAddress" },
      { label: "Sender Name", key: "senderName" },
      { label: "Sender Address", key: "senderAddress" },
      { label: "Contract Date", key: "contractDate" },
      { label: "Contract Subject", key: "contractSubject" },
      { label: "Breach Details", key: "breachDetails" },
      { label: "Remedy Period (Days)", key: "remedyPeriod" },
    ],
    "notice-for-recovery-of-dues": [
      { label: "To Party", key: "toParty" },
      { label: "From Party", key: "fromParty" },
      { label: "Amount Due", key: "amountDue" },
      { label: "Transaction Reference", key: "transactionRef" },
      { label: "Transaction Date", key: "transactionDate" },
      { label: "Due Days", key: "dueDays" },
    ],
  };

export const exampleDrafts: { [key: string]: string } = {
  "payment-reminder": paymentReminderExample,
  "termination-notice": terminationNotice,
  "legal-demand-notice": legalDemandNotice,
  "non-disclosure-agreement": nonDisclosureAgreement,
  "employment-offer-letter": employmentOfferLetter,
  "lease-agreement": leaseAgreement,
  "service-agreement": serviceAgreement,
  "invoice-for-service": invoiceForServices,
  "loan-agreement": loanAgreement,
  "consulting-agreement": consultingAgreement,
  "employment-contract": employmentContract,
  "partnership-agreement": partnershipAgreement,
  "joint-venture-agreement": jointVentureAgreement,
  "promissory-note": promissoryNote, 
  "shareholders-agreement": shareholdersAgreement,
  "memorandum-of-understanding": memorandumOfUnderstanding,
  "notice-to-vacate": noticeToVacate,
  "notice-for-breach-of-contract": noticeForBreachOfContract,
  "notice-for-recovery-of-dues": noticeForRecoveryOfDues,//done
};
