export const fieldSchema= { 
    "payment-reminder": [
      { label: "Date", key: "date" },
      { label: "Reference Number", key: "refNo" },
      { label: "Lawyer Name", key: "lawyerName" },
      { label: "Lawyer Address", key: "lawyerAddress" },
      { label: "Lawyer Phone", key: "lawyerPhone" },
      { label: "Lawyer Email", key: "lawyerEmail" },
      { label: "Recipient Name", key: "recipientName" },
      { label: "Recipient Address", key: "recipientAddress" },
      { label: "Outstanding Amount", key: "amount" },
      { label: "Your Company Name", key: "companyName" },
      { label: "Business Description", key: "businessDescription" },
      { label: "Agreement Date", key: "agreementDate" },
      { label: "Invoice Details", key: "invoiceDetails" },
      { label: "Your Address", key: "yourAddress" },
      { label: "Bank Name", key: "bankName" },
      { label: "Account Holder", key: "accountHolder" },
      { label: "Account Number", key: "accountNumber" },
      { label: "IFSC Code", key: "ifscCode" },
      { label: "Days to Comply", key: "days" },
    ],
    "termination-notice": [
      { label: "To Employee", key: "toEmployee" },
      { label: "From Company", key: "fromCompany" },
      { label: "Reason", key: "reason" },
      { label: "Termination Date", key: "date" },
    ],
    "legal-demand-notice": [
      { label: "Date", key: "date" },
      { label: "To Party", key: "toParty" },
      { label: "Recipient Address", key: "recipientAddress" },
      { label: "From Lawyer", key: "fromLawyer" },
      { label: "Claim Details", key: "claimDetails" },
      { label: "Days to Comply", key: "days" },
    ],
  };