// app/layout.tsx (server)
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import ClientProviders from "./components/ClientProvider";
import ProtectedLayout from "./components/ProtectedLayer";
import { Analytics } from "@vercel/analytics/next";

const geistSans = Geist({ variable: "--font-geist-sans", subsets: ["latin"] });
const geistMono = Geist_Mono({ variable: "--font-geist-mono", subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Lexx",
  description: "Generated by dumb genius",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`dark:bg-stone-950 text-stone-100 ${geistSans.variable} ${geistMono.variable} antialiased`}>
        <ClientProviders>
          <ProtectedLayout>
            {children}
            <Analytics />
          </ProtectedLayout>
        </ClientProviders>
      </body>
    </html>
  );
}
