import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { AuthProvider } from "../../context/AuthContext";
import ProtectedLayout from "./components/ProtectedLayer";
import { ThemeProvider } from "next-themes";
import { Analytics } from "@vercel/analytics/next"
import { LoadingProvider } from "./components/Loading";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Lexx",
  description: "Generated by dumb genius",
};


export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`bg-stone-950 text-stone-100 ${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ThemeProvider attribute="class" defaultTheme="dark">
        <AuthProvider>
          <ProtectedLayout>
            <LoadingProvider>
              {children}
            </LoadingProvider>
            <Analytics />
          </ProtectedLayout>
        </AuthProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
